### ISSUE TITLE
No beans of Service Client class 

### ISSUE THREAD

**Issue by myksao** [ButterCam/sisyphus#516]
First and foremost, I'd like to express my gratitude to the open-source library authors for this valuable tool. 
 
After attempting to use the generated Grpc Service Client class, I came across an issue. I would appreciate any help. 

```
 @Autowired
 lateinit var echo: Echo.Client
```
 Error
` 
 Could not autowire. No beans of Service Client class.
 Consider defining a bean of type 'com.google.showcase.v1beta1.Echo$Client' in your configuration.
`

**Comment by devkanro** [comment]
Client can be autowired by three way:
1. [Local Service Discovery](https://sisyphus.bybutter.com/docs/advanced-guides/service-discover#local-service-discovery) 
2. [Service discovery in k8s cluster](https://sisyphus.bybutter.com/docs/advanced-guides/service-discover#service-discovery-in-k8s-cluster)
3. Service discovery with properties config
  You need config host in your `application.yaml`, more config check the [properties](https://github.com/ButterCam/sisyphus/blob/master/middleware/sisyphus-grpc-client/src/main/kotlin/com/bybutter/sisyphus/middleware/grpc/GrpcChannelProperty.kt)
```yaml
sisyphus:
  grpc:
    echoService:
      name: echo
      target: localhost:9090
      services:
      - com.google.grpc.sample.Echo # rpc service class with package
```
